# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asset_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'asset_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61sset_service.proto\x12\x05\x41sset\"\x1d\n\x0c\x41lohaRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"]\n\rAlohaResponse\x12&\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x11.Asset.StatusCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x05\"#\n\x14\x44ownloadAssetRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"V\n\x15\x44ownloadAssetResponse\x12&\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x11.Asset.StatusCode\x12\x15\n\rerror_message\x18\x02 \x01(\t*$\n\nStatusCode\x12\x0b\n\x07Success\x10\x00\x12\t\n\x05\x45rror\x10\x01\x32\x8d\x01\n\x0bGrpcService\x12\x32\n\x05\x41loha\x12\x13.Asset.AlohaRequest\x1a\x14.Asset.AlohaResponse\x12J\n\rDownloadAsset\x12\x1b.Asset.DownloadAssetRequest\x1a\x1c.Asset.DownloadAssetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=281
  _globals['_STATUSCODE']._serialized_end=317
  _globals['_ALOHAREQUEST']._serialized_start=30
  _globals['_ALOHAREQUEST']._serialized_end=59
  _globals['_ALOHARESPONSE']._serialized_start=61
  _globals['_ALOHARESPONSE']._serialized_end=154
  _globals['_DOWNLOADASSETREQUEST']._serialized_start=156
  _globals['_DOWNLOADASSETREQUEST']._serialized_end=191
  _globals['_DOWNLOADASSETRESPONSE']._serialized_start=193
  _globals['_DOWNLOADASSETRESPONSE']._serialized_end=279
  _globals['_GRPCSERVICE']._serialized_start=320
  _globals['_GRPCSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
