# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import edit_service_pb2 as edit__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edit_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Aloha = channel.unary_unary(
                '/SceneEdit.GrpcService/Aloha',
                request_serializer=edit__service__pb2.AlohaRequest.SerializeToString,
                response_deserializer=edit__service__pb2.AlohaResponse.FromString,
                _registered_method=True)
        self.AddActor = channel.unary_unary(
                '/SceneEdit.GrpcService/AddActor',
                request_serializer=edit__service__pb2.AddActorRequest.SerializeToString,
                response_deserializer=edit__service__pb2.AddActorResponse.FromString,
                _registered_method=True)
        self.AddGroup = channel.unary_unary(
                '/SceneEdit.GrpcService/AddGroup',
                request_serializer=edit__service__pb2.AddGroupRequest.SerializeToString,
                response_deserializer=edit__service__pb2.AddGroupResponse.FromString,
                _registered_method=True)
        self.SetActorTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/SetActorTransform',
                request_serializer=edit__service__pb2.SetActorTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetActorTransformResponse.FromString,
                _registered_method=True)
        self.GetPendingOperations = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingOperations',
                request_serializer=edit__service__pb2.GetPendingOperationsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingOperationsResponse.FromString,
                _registered_method=True)
        self.GetPendingActorTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingActorTransform',
                request_serializer=edit__service__pb2.GetPendingActorTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingActorTransformResponse.FromString,
                _registered_method=True)
        self.GetSyncFromMujocoToScene = channel.unary_unary(
                '/SceneEdit.GrpcService/GetSyncFromMujocoToScene',
                request_serializer=edit__service__pb2.GetSyncFromMujocoToSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetSyncFromMujocoToSceneResponse.FromString,
                _registered_method=True)
        self.SetSyncFromMujocoToScene = channel.unary_unary(
                '/SceneEdit.GrpcService/SetSyncFromMujocoToScene',
                request_serializer=edit__service__pb2.SetSyncFromMujocoToSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetSyncFromMujocoToSceneResponse.FromString,
                _registered_method=True)
        self.ClearScene = channel.unary_unary(
                '/SceneEdit.GrpcService/ClearScene',
                request_serializer=edit__service__pb2.ClearSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.ClearSceneResponse.FromString,
                _registered_method=True)
        self.GetActorAssets = channel.unary_unary(
                '/SceneEdit.GrpcService/GetActorAssets',
                request_serializer=edit__service__pb2.GetActorAssetsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetActorAssetsResponse.FromString,
                _registered_method=True)
        self.GetPendingSelectionChange = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingSelectionChange',
                request_serializer=edit__service__pb2.GetPendingSelectionChangeRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingSelectionChangeResponse.FromString,
                _registered_method=True)
        self.GetPendingAddItem = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingAddItem',
                request_serializer=edit__service__pb2.GetPendingAddItemRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingAddItemResponse.FromString,
                _registered_method=True)
        self.SetSelection = channel.unary_unary(
                '/SceneEdit.GrpcService/SetSelection',
                request_serializer=edit__service__pb2.SetSelectionRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetSelectionResponse.FromString,
                _registered_method=True)
        self.SaveBodyTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/SaveBodyTransform',
                request_serializer=edit__service__pb2.SaveBodyTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SaveBodyTransformResponse.FromString,
                _registered_method=True)
        self.RestoreBodyTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/RestoreBodyTransform',
                request_serializer=edit__service__pb2.RestoreBodyTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.RestoreBodyTransformResponse.FromString,
                _registered_method=True)
        self.DeleteActor = channel.unary_unary(
                '/SceneEdit.GrpcService/DeleteActor',
                request_serializer=edit__service__pb2.DeleteActorRequest.SerializeToString,
                response_deserializer=edit__service__pb2.DeleteActorResponse.FromString,
                _registered_method=True)
        self.RenameActor = channel.unary_unary(
                '/SceneEdit.GrpcService/RenameActor',
                request_serializer=edit__service__pb2.RenameActorRequest.SerializeToString,
                response_deserializer=edit__service__pb2.RenameActorResponse.FromString,
                _registered_method=True)
        self.ReParentActor = channel.unary_unary(
                '/SceneEdit.GrpcService/ReParentActor',
                request_serializer=edit__service__pb2.ReParentActorRequest.SerializeToString,
                response_deserializer=edit__service__pb2.ReParentActorResponse.FromString,
                _registered_method=True)
        self.GetWindowId = channel.unary_unary(
                '/SceneEdit.GrpcService/GetWindowId',
                request_serializer=edit__service__pb2.GetWindowIdRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetWindowIdResponse.FromString,
                _registered_method=True)
        self.GetGeneratePos = channel.unary_unary(
                '/SceneEdit.GrpcService/GetGeneratePos',
                request_serializer=edit__service__pb2.GetGeneratePosRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetGeneratePosResponse.FromString,
                _registered_method=True)


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Aloha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActorTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingActorTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncFromMujocoToScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSyncFromMujocoToScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingSelectionChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingAddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSelection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveBodyTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreBodyTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReParentActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWindowId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGeneratePos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Aloha': grpc.unary_unary_rpc_method_handler(
                    servicer.Aloha,
                    request_deserializer=edit__service__pb2.AlohaRequest.FromString,
                    response_serializer=edit__service__pb2.AlohaResponse.SerializeToString,
            ),
            'AddActor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddActor,
                    request_deserializer=edit__service__pb2.AddActorRequest.FromString,
                    response_serializer=edit__service__pb2.AddActorResponse.SerializeToString,
            ),
            'AddGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGroup,
                    request_deserializer=edit__service__pb2.AddGroupRequest.FromString,
                    response_serializer=edit__service__pb2.AddGroupResponse.SerializeToString,
            ),
            'SetActorTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActorTransform,
                    request_deserializer=edit__service__pb2.SetActorTransformRequest.FromString,
                    response_serializer=edit__service__pb2.SetActorTransformResponse.SerializeToString,
            ),
            'GetPendingOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingOperations,
                    request_deserializer=edit__service__pb2.GetPendingOperationsRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingOperationsResponse.SerializeToString,
            ),
            'GetPendingActorTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingActorTransform,
                    request_deserializer=edit__service__pb2.GetPendingActorTransformRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingActorTransformResponse.SerializeToString,
            ),
            'GetSyncFromMujocoToScene': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncFromMujocoToScene,
                    request_deserializer=edit__service__pb2.GetSyncFromMujocoToSceneRequest.FromString,
                    response_serializer=edit__service__pb2.GetSyncFromMujocoToSceneResponse.SerializeToString,
            ),
            'SetSyncFromMujocoToScene': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSyncFromMujocoToScene,
                    request_deserializer=edit__service__pb2.SetSyncFromMujocoToSceneRequest.FromString,
                    response_serializer=edit__service__pb2.SetSyncFromMujocoToSceneResponse.SerializeToString,
            ),
            'ClearScene': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearScene,
                    request_deserializer=edit__service__pb2.ClearSceneRequest.FromString,
                    response_serializer=edit__service__pb2.ClearSceneResponse.SerializeToString,
            ),
            'GetActorAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorAssets,
                    request_deserializer=edit__service__pb2.GetActorAssetsRequest.FromString,
                    response_serializer=edit__service__pb2.GetActorAssetsResponse.SerializeToString,
            ),
            'GetPendingSelectionChange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingSelectionChange,
                    request_deserializer=edit__service__pb2.GetPendingSelectionChangeRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingSelectionChangeResponse.SerializeToString,
            ),
            'GetPendingAddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingAddItem,
                    request_deserializer=edit__service__pb2.GetPendingAddItemRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingAddItemResponse.SerializeToString,
            ),
            'SetSelection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSelection,
                    request_deserializer=edit__service__pb2.SetSelectionRequest.FromString,
                    response_serializer=edit__service__pb2.SetSelectionResponse.SerializeToString,
            ),
            'SaveBodyTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveBodyTransform,
                    request_deserializer=edit__service__pb2.SaveBodyTransformRequest.FromString,
                    response_serializer=edit__service__pb2.SaveBodyTransformResponse.SerializeToString,
            ),
            'RestoreBodyTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreBodyTransform,
                    request_deserializer=edit__service__pb2.RestoreBodyTransformRequest.FromString,
                    response_serializer=edit__service__pb2.RestoreBodyTransformResponse.SerializeToString,
            ),
            'DeleteActor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteActor,
                    request_deserializer=edit__service__pb2.DeleteActorRequest.FromString,
                    response_serializer=edit__service__pb2.DeleteActorResponse.SerializeToString,
            ),
            'RenameActor': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameActor,
                    request_deserializer=edit__service__pb2.RenameActorRequest.FromString,
                    response_serializer=edit__service__pb2.RenameActorResponse.SerializeToString,
            ),
            'ReParentActor': grpc.unary_unary_rpc_method_handler(
                    servicer.ReParentActor,
                    request_deserializer=edit__service__pb2.ReParentActorRequest.FromString,
                    response_serializer=edit__service__pb2.ReParentActorResponse.SerializeToString,
            ),
            'GetWindowId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWindowId,
                    request_deserializer=edit__service__pb2.GetWindowIdRequest.FromString,
                    response_serializer=edit__service__pb2.GetWindowIdResponse.SerializeToString,
            ),
            'GetGeneratePos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeneratePos,
                    request_deserializer=edit__service__pb2.GetGeneratePosRequest.FromString,
                    response_serializer=edit__service__pb2.GetGeneratePosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SceneEdit.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SceneEdit.GrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Aloha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/Aloha',
            edit__service__pb2.AlohaRequest.SerializeToString,
            edit__service__pb2.AlohaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/AddActor',
            edit__service__pb2.AddActorRequest.SerializeToString,
            edit__service__pb2.AddActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/AddGroup',
            edit__service__pb2.AddGroupRequest.SerializeToString,
            edit__service__pb2.AddGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActorTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetActorTransform',
            edit__service__pb2.SetActorTransformRequest.SerializeToString,
            edit__service__pb2.SetActorTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingOperations',
            edit__service__pb2.GetPendingOperationsRequest.SerializeToString,
            edit__service__pb2.GetPendingOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingActorTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingActorTransform',
            edit__service__pb2.GetPendingActorTransformRequest.SerializeToString,
            edit__service__pb2.GetPendingActorTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncFromMujocoToScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetSyncFromMujocoToScene',
            edit__service__pb2.GetSyncFromMujocoToSceneRequest.SerializeToString,
            edit__service__pb2.GetSyncFromMujocoToSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSyncFromMujocoToScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetSyncFromMujocoToScene',
            edit__service__pb2.SetSyncFromMujocoToSceneRequest.SerializeToString,
            edit__service__pb2.SetSyncFromMujocoToSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/ClearScene',
            edit__service__pb2.ClearSceneRequest.SerializeToString,
            edit__service__pb2.ClearSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetActorAssets',
            edit__service__pb2.GetActorAssetsRequest.SerializeToString,
            edit__service__pb2.GetActorAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingSelectionChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingSelectionChange',
            edit__service__pb2.GetPendingSelectionChangeRequest.SerializeToString,
            edit__service__pb2.GetPendingSelectionChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingAddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingAddItem',
            edit__service__pb2.GetPendingAddItemRequest.SerializeToString,
            edit__service__pb2.GetPendingAddItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSelection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetSelection',
            edit__service__pb2.SetSelectionRequest.SerializeToString,
            edit__service__pb2.SetSelectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveBodyTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SaveBodyTransform',
            edit__service__pb2.SaveBodyTransformRequest.SerializeToString,
            edit__service__pb2.SaveBodyTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreBodyTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/RestoreBodyTransform',
            edit__service__pb2.RestoreBodyTransformRequest.SerializeToString,
            edit__service__pb2.RestoreBodyTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/DeleteActor',
            edit__service__pb2.DeleteActorRequest.SerializeToString,
            edit__service__pb2.DeleteActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/RenameActor',
            edit__service__pb2.RenameActorRequest.SerializeToString,
            edit__service__pb2.RenameActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReParentActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/ReParentActor',
            edit__service__pb2.ReParentActorRequest.SerializeToString,
            edit__service__pb2.ReParentActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWindowId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetWindowId',
            edit__service__pb2.GetWindowIdRequest.SerializeToString,
            edit__service__pb2.GetWindowIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGeneratePos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetGeneratePos',
            edit__service__pb2.GetGeneratePosRequest.SerializeToString,
            edit__service__pb2.GetGeneratePosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
