# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import edit_service_pb2 as edit__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edit_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Aloha = channel.unary_unary(
                '/SceneEdit.GrpcService/Aloha',
                request_serializer=edit__service__pb2.AlohaRequest.SerializeToString,
                response_deserializer=edit__service__pb2.AlohaResponse.FromString,
                _registered_method=True)
        self.AddActor = channel.unary_unary(
                '/SceneEdit.GrpcService/AddActor',
                request_serializer=edit__service__pb2.AddActorRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SimpleResponse.FromString,
                _registered_method=True)
        self.SetActorTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/SetActorTransform',
                request_serializer=edit__service__pb2.SetActorTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SimpleResponse.FromString,
                _registered_method=True)
        self.GetPendingOperations = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingOperations',
                request_serializer=edit__service__pb2.GetPendingOperationsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingOperationsResponse.FromString,
                _registered_method=True)
        self.GetPendingActorTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingActorTransform',
                request_serializer=edit__service__pb2.GetPendingActorTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingActorTransformResponse.FromString,
                _registered_method=True)


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Aloha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActorTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingActorTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Aloha': grpc.unary_unary_rpc_method_handler(
                    servicer.Aloha,
                    request_deserializer=edit__service__pb2.AlohaRequest.FromString,
                    response_serializer=edit__service__pb2.AlohaResponse.SerializeToString,
            ),
            'AddActor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddActor,
                    request_deserializer=edit__service__pb2.AddActorRequest.FromString,
                    response_serializer=edit__service__pb2.SimpleResponse.SerializeToString,
            ),
            'SetActorTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActorTransform,
                    request_deserializer=edit__service__pb2.SetActorTransformRequest.FromString,
                    response_serializer=edit__service__pb2.SimpleResponse.SerializeToString,
            ),
            'GetPendingOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingOperations,
                    request_deserializer=edit__service__pb2.GetPendingOperationsRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingOperationsResponse.SerializeToString,
            ),
            'GetPendingActorTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingActorTransform,
                    request_deserializer=edit__service__pb2.GetPendingActorTransformRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingActorTransformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SceneEdit.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SceneEdit.GrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Aloha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/Aloha',
            edit__service__pb2.AlohaRequest.SerializeToString,
            edit__service__pb2.AlohaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/AddActor',
            edit__service__pb2.AddActorRequest.SerializeToString,
            edit__service__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActorTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetActorTransform',
            edit__service__pb2.SetActorTransformRequest.SerializeToString,
            edit__service__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingOperations',
            edit__service__pb2.GetPendingOperationsRequest.SerializeToString,
            edit__service__pb2.GetPendingOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingActorTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingActorTransform',
            edit__service__pb2.GetPendingActorTransformRequest.SerializeToString,
            edit__service__pb2.GetPendingActorTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
