orcagym_addresses: ["localhost:50051"]
agent_name: "go2"
agent_spawnable_name: "go2_usda"

model_file: 
  "flat_terrain": "//home/superfhwl/repo/OrcaGym/examples/legged_gym/trained_models_tmp/go2_2048_2025-08-11_12-31-08/go2_follow_command.zip_rough_terrain_iteration_500.zip"
  "rough_terrain": "/home/superfhwl/repo/OrcaGym/examples/legged_gym/trained_models_tmp/go2_2048_2025-08-11_12-31-08/go2_follow_command.zip_advanced_moving_iteration_1000.zip"
  "stand_still": "/home/superfhwl/repo/OrcaGym/examples/legged_gym/trained_models_tmp/go2_2048_2025-08-11_12-31-08/go2_follow_command.zip_basic_moving_iteration_100.zip"

ctrl_device: "keyboard"

command_model:
  "flat_terrain":
    "forward": "flat_terrain"
    "backward": "stand_still"
    "stand_still": "stand_still"
  "rough_terrain":
    "forward": "rough_terrain"
    "backward": "rough_terrain"
    "stand_still": "rough_terrain"
  
terrain_spawnable_names: ["terrain_test_usda"]
