orcagym_addresses: ["localhost:50051"]
agent_name: "go2"
agent_spawnable_name: "go2_usda"

model_file: 
  "flat_terrain": "./test/go2_follow_command.zip_iteration_200.zip"
  "rough_terrain": "./test/go2_follow_command.zip_iteration_900.zip"
  "stand_still": "./test/go2_stand_still.zip_iteration_500.zip"

ctrl_device: "keyboard"

command_model:
  "flat_terrain":
    "forward": "flat_terrain"
    "backward": "stand_still"
    "turn": "rough_terrain"
  "rough_terrain":
    "forward": "rough_terrain"
    "backward": "stand_still"
    "turn": "rough_terrain"
  "stand_still": "stand_still"
  
terrain_spawnable_names: ["terrain_test_usda"]
