orcagym_addresses: ["localhost:50051"]
agent_name: "go2"
agent_spawnable_name: "go2_usda"

model_file: 
  "flat_terrain": "/home/orca/repo/OrcaGym/examples/legged_gym/trained_models_tmp/go2_2048_2025-08-12_12-39-14/go2_stand_still.zip_iteration_200.zip"
  "rough_terrain": "/home/orca/repo/OrcaGym/examples/legged_gym/trained_models_tmp/go2_2048_2025-08-12_12-39-14/go2_stand_still.zip_iteration_200.zip"
  "stand_still": "/home/orca/repo/OrcaGym/examples/legged_gym/trained_models_tmp/go2_2048_2025-08-12_15-22-41/go2_stand_still.zip_stand_still_iteration_500.zip"

ctrl_device: "keyboard"

command_model:
  "flat_terrain":
    "forward": "flat_terrain"
    "backward": "flat_terrain"
    "stand_still": "stand_still"
    "trun": "stand_still"
  "rough_terrain":
    "forward": "rough_terrain"
    "backward": "rough_terrain"
    "stand_still": "rough_terrain"
    "trun": "rough_terrain"
  
terrain_spawnable_names: ["terrain_test_usda"]
