orcagym_addresses: ["localhost:50051"]
agent_name: "Lite3"
agent_spawnable_name: "lite3_usda"

model_file: 
  "flat_terrain": "./test/Lite3_follow_command.zip_flat_terrain_iteration_300.zip"
  "rough_terrain": "./test/Lite3_follow_command.zip_rough_terrain_iteration_600.zip"
  "stand_still": "./test/Lite3_follow_command.zip_rough_terrain_iteration_600.zip"

ctrl_device: "keyboard"

command_model:
  "flat_terrain":
    "forward": "flat_terrain"
    "backward": "stand_still"
  "rough_terrain":
    "forward": "rough_terrain"
    "backward": "stand_still"
  "stand_still": "stand_still"
  
terrain_spawnable_names: ["terrain_test_usda"]
