orcagym_addresses: ["localhost:50051"]
agent_name: "go2"
agent_spawnable_name: "go2_usda"
training_episode: 200
task: "follow_command"

training:
  subenv_num: 32
  agent_num: 32
  render_mode: "none"
  terrain_spawnable_names: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
  curriculum_list:
    follow_command:
      - name: "basic_moving"
        milestone: 50
      - name: "flat_terrain"
        milestone: 200
      - name: "rough_terrain"
        milestone: 1000
      - name: "advanced_moving"
        milestone: 1500
    stand_still:
      - name: "basic_moving"
        milestone: 500

testing:
  subenv_num: 1
  agent_num: 8
  render_mode: "human"
  terrain_spawnable_names: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
  curriculum_list:
    follow_command:
      - name: "flat_terrain"
        milestone: 2000
    stand_still:
      - name: "basic_moving"
        milestone: 2000

play:
  subenv_num: 1
  agent_num: 1
  render_mode: "human"
  terrain_spawnable_names: ["terrain_test_usda"]
  curriculum_list:
    follow_command:
      - name: "flat_terrain"
        milestone: 2000
    stand_still:
      - name: "basic_moving"
        milestone: 2000