framework: "sb3"
orcagym_addresses: ["localhost:50051"]
agent_name: "Lite3"
agent_spawnable_name: "lite3_usda"
training_episode: 200
task: "follow_command"

training:
  subenv_num: 64
  agent_num: 32
  render_mode: "none"
  terrain_spawnable_names: 
    follow_command: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
    stand_still: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
  curriculum_list:
    follow_command:
      - name: "basic_moving"
        milestone: 100
      - name: "flat_terrain"
        milestone: 300
      - name: "rough_terrain"
        milestone: 1000
    stand_still:
      - name: "stand_still"
        milestone: 500

testing:
  subenv_num: 1
  agent_num: 8
  render_mode: "human"
  terrain_spawnable_names: 
    follow_command: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
  curriculum_list:
    follow_command:
      - name: "flat_terrain"
        milestone: 2000

play:
  subenv_num: 1
  agent_num: 1
  render_mode: "human"
  terrain_spawnable_names: 
    follow_command: ["terrain_test_usda"]
  curriculum_list:
    follow_command:
      - name: "flat_terrain"
        milestone: 2000