# config.yaml
basic:
  parallelism_num: 1
  datalink_auth_config: "/home/orcatest/GameLauncher/orcasim.json"
  orcasim_path: "/home/orcatest/GameLauncher/OrcaProject.GameLauncher"
  level: "yaodian_test"
  levelorca: "yaodian0723_01_sh_b00_shijue"
  # levelorca: "yaodian0721"
connection:
  orcagym_address: "localhost:50051"
  agent_names: "openloong_gripper_2f85_fix_base_usda"
  pico_ports: "8001"

mode:
  run_mode: "augmentation"
  action_type: "joint_pos"

task:
  task_config: "ayaodian.yaml"
  dataset: "/home/orcatest/Orcagym_kps/OrcaGym/examples/openpi/processed_datasets_tmp/combined_DualArmEnv_1_0_0_yaodian_guiji_task_2025-07-10_14-23-25.hdf5"

advanced:
  record_length: 1200
 
  playback_mode: "random"
  rollout_times: 10
  augmented_noise: 0.005
  augmented_rounds: 20
  teleoperation_rounds: 100
  sample_range: 0.0
  realtime_playback: 'True'
  withvideo: 'True'
  index: 0
  sync_codec: 'False'
  useNvenc: 1
