# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x7f\n\x10InferenceRequest\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\x12\x14\n\x0c\x64\x65sired_goal\x18\x02 \x03(\x02\x12\x15\n\rachieved_goal\x18\x03 \x03(\x02\x12\x12\n\nmodel_type\x18\x04 \x01(\t\x12\x15\n\rdeterministic\x18\x05 \x01(\x08\"[\n\x11InferenceResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\x12\x0e\n\x06states\x18\x02 \x03(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\"F\n\x15\x42\x61tchInferenceRequest\x12-\n\x08requests\x18\x01 \x03(\x0b\x32\x1b.inference.InferenceRequest\"I\n\x16\x42\x61tchInferenceResponse\x12/\n\tresponses\x18\x01 \x03(\x0b\x32\x1c.inference.InferenceResponse2\xad\x01\n\x10InferenceService\x12\x44\n\x07Predict\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponse\x12S\n\x0c\x42\x61tchPredict\x12 .inference.BatchInferenceRequest\x1a!.inference.BatchInferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=157
  _globals['_INFERENCERESPONSE']._serialized_start=159
  _globals['_INFERENCERESPONSE']._serialized_end=250
  _globals['_BATCHINFERENCEREQUEST']._serialized_start=252
  _globals['_BATCHINFERENCEREQUEST']._serialized_end=322
  _globals['_BATCHINFERENCERESPONSE']._serialized_start=324
  _globals['_BATCHINFERENCERESPONSE']._serialized_end=397
  _globals['_INFERENCESERVICE']._serialized_start=400
  _globals['_INFERENCESERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
