orcagym_addresses: ["localhost:50051"]
agent_name: "go2"
agent_spawnable_name: "go2_usda"

model_file: 
  "flat_terrain": "/home/superfhwl/download/go2_follow_command_flat_terrain_iteration_300.zip"
  "rough_terrain": "/home/superfhwl/download/go2_follow_command_rough_terrain_iteration_1000.zip"

ctrl_device: "keyboard"

command_model:
  "flat_terrain":
  "rough_terrain":
  
terrain_spawnable_names: ["terrain_test_usda"]
