framework: "rllib"
orcagym_addresses: ["192.168.1.100:50051"]    # 因为worker节点要远程访问OrcaLab，所以要配置你运行OrcaLab的节点ip地址，推荐使用有线网口，尽量不要用无线网口
ray_cluster_address: "ray://192.168.1.100:6379"  # Ray集群地址，是你启动head节点的ip地址，推荐使用有线网口，尽量不要用无线网口
agent_name: "Lite3"
agent_spawnable_name: "lite3_usda"
task: "flat_terrain"
env_name: "LeggedGym"

# 集群训练专用配置
training:
  max_episode_steps: 1000
  num_env_runners: 32             # 根据集群可用CPU核数来配置。
  num_envs_per_env_runner: 256    # 必须是 64 的倍数，一个Mujoco Instance支持64个agent是最合理的，这是默认配置
  async_env_runner: True
  iter: 2000
  render_mode: none
  terrain_spawnable_names: 
    flat_terrain: ["terrain_ellipsoid_low_usda", "terrain_stair_low_flat_usda", "terrain_brics_low_usda"]
    rough_terrain: ["terrain_stair_low_usda", "terrain_stair_low_flat_usda", "terrain_brics_low_usda", "terrain_slope_5_usda", "terrain_stair_high_usda", "terrain_brics_high_usda", "terrain_slope_10_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000
    rough_terrain:
      - name: "rough_terrain"
        milestone: 2000

testing:
  agent_name: "Lite3_000"
  max_episode_steps: 1000
  render_mode: human
  num_env_runners: 1         
  num_envs_per_env_runner: 1    
  async_env_runner: True
  iter: 2000
  terrain_spawnable_names: 
    flat_terrain: ["terrain_ellipsoid_low_usda", "terrain_stair_low_flat_usda", "terrain_brics_low_usda"]
    rough_terrain: ["terrain_stair_low_usda", "terrain_stair_low_flat_usda", "terrain_brics_low_usda", "terrain_slope_5_usda", "terrain_stair_high_usda", "terrain_brics_high_usda", "terrain_slope_10_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000
    rough_terrain:
      - name: "rough_terrain"
        milestone: 2000

playing:
  agent_name: "Lite3_000"
  max_episode_steps: 1000
  render_mode: human 