framework: "rllib"
orcagym_addresses: ["localhost:50051"]
agent_name: "go2"
agent_spawnable_name: "go2_usda"
task: "follow_command"
env_name: "LeggedGym"

training:
  max_episode_steps: 1000
  num_env_runners: 16
  num_envs_per_env_runner: 32
  async_env_runner: True
  iter: 1000
  render_mode: none
  terrain_spawnable_names: 
    follow_command: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
    stand_still: []

testing:
  agent_name: "go2_000"
  max_episode_steps: 1000
  render_mode: human

playing:
  agent_name: "go2_000"
  max_episode_steps: 1000
  render_mode: human