framework: "sb3"
orcagym_addresses: ["localhost:50051"]
agent_name: "Lite3"
agent_asset_path: "assets/prefabs/lite3_usda"
training_episode: 100
task: "flat_terrain"

training:
  subenv_num: 32
  agent_num: 32
  render_mode: "none"
  terrain_asset_paths: 
    flat_terrain: ["assets/prefabs/terrain_ellipsoid_low_usda", "assets/prefabs/terrain_stair_low_flat_usda", "assets/prefabs/terrain_brics_low_usda"]
    rough_terrain: ["assets/prefabs/terrain_stair_low_usda", "assets/prefabs/terrain_stair_low_flat_usda", "assets/prefabs/terrain_brics_low_usda", "assets/prefabs/terrain_slope_5_usda", "assets/prefabs/terrain_stair_high_usda", "assets/prefabs/terrain_brics_high_usda", "assets/prefabs/terrain_slope_10_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 1500
    rough_terrain:
      - name: "basic_moving"
        milestone: 100
      - name: "rough_terrain"
        milestone: 3000

testing:
  subenv_num: 1
  agent_num: 8
  render_mode: "human"
  terrain_asset_paths: 
    flat_terrain: ["terrain_perlin_rough_slope_usda", "terrain_perlin_smooth_slope_usda", "terrain_perlin_rough_usda", "terrain_perlin_smooth_usda", "terrain_stair_high_usda", "terrain_stair_low_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000

play:
  subenv_num: 1
  agent_num: 1
  render_mode: "human"
  terrain_asset_paths: 
    flat_terrain: ["terrain_test_usda"]
  curriculum_list:
    flat_terrain:
      - name: "flat_terrain"
        milestone: 2000