# config/usdz_processing.yaml
version: "1.0"

default_settings:
  transform_options:
    scale: 1.0
  collision_options:
    collider_type: "bounding_box"  # "bounding_box" , "convex_hull"
    split_mesh: false
    max_split_mesh_number: 64
    merge_threshold: 0.9          # 两个bounding box 之间的重合度
  physics_options:
    free_joint: true
    density: 1000.0
    mass: 0.0
  debug_options:
    visualize_obj: false


files:
  - filename: "Cup_of_Coffee.usdz"  
    transform_options:
      scale: 0.1
    collision_options:
      collider_type: "bounding_box"
      split_mesh: true
      max_split_mesh_number: 64
      merge_threshold: 0.9
      merge_iterations: 10
    physics_options:
      free_joint: true
      density: 1000.0
      mass: 1.0


  - filename: "Office_Desk_7_MB.usdz" 
    transform_options:
      scale: 0.75
    collision_options:
      collider_type: "bounding_box"
      split_mesh: true
      max_split_mesh_number: 32
      merge_threshold: 0.9
      merge_iterations: 10

  - filename: "Round_Table.usdz"
    transform_options:
      scale: 0.3
    collision_options:
      collider_type: "bounding_box"
      split_mesh: true
      max_split_mesh_number: 10
      merge_threshold: 0.9
      merge_iterations: 10


  - filename: "Fully_textured_tank.usdz"
    collision_options:
      collider_type: "bounding_box"
      split_mesh: true
      max_split_mesh_number: 64
      merge_threshold: 0.9
      merge_iterations: 10


  - filename: "Railway_Signal_Box_-_Bytom_Poland.usdz"
    transform_options:
      scale: 10
    physics_options:
      free_joint: false
      density: 1000.0
      mass: 1.0
    collision_options:
      collider_type: "bounding_box"
      split_mesh: true
      max_split_mesh_number: 80
      merge_threshold: 0.9
      merge_iterations: 10

  - filename: "Cart_Basket.usdz"  
    transform_options:
      scale: 0.333
    collision_options:
      collider_type: "bounding_box"
      split_mesh: true
      max_split_mesh_number: 80
      merge_threshold: 0.9
      merge_iterations: 10