# config/usdz_processing.yaml
version: "1.0"

default_settings:
  physics_options:
    collider_type: "bounding_box"
    free_joint: false

files:
  - filename: "cup/Cup_of_Coffee.usdz"  
    physics_options:
      free_joint: true

  - filename: "table/Office_Desk_7_MB.usdz" 

  - filename: "table/Round_Table.usdz"
    physics_options:
      collider_type: "convex_hull"
