# config/usdz_processing.yaml
version: "1.0"

default_settings:
  transform_options:
    scale: 1.0

  collision_options:
    collider_type: "bounding_box"

  physics_options:
    free_joint: true
    density: 1000.0

files:
  - filename: "Cup_of_Coffee.usdz"  
    transform_options:
      scale: 0.1

  - filename: "Office_Desk_7_MB.usdz" 
    transform_options:
      scale: 0.75

  - filename: "Round_Table.usdz"
    transform_options:
      scale: 0.5

  - filename: "Fully_textured_tank.usdz"

  - filename: "Railway_Signal_Box_-_Bytom_Poland.usdz"
    transform_options:
      scale: 10
    physics_options:
      free_joint: false
